Repository prezly/theme-nextjs-bea, pull requests merged in 2024-01, with the labels that each got.

#1062 [DEV-12039] Optimize - Middleware to get newsroom locales from header
  middleware.ts
Labels: enhancement

#1065 [DEV-12325] Fix - Search overlay displaying categories with no public stories
  modules/Header/Categories.tsx
  modules/Header/Header.tsx
  modules/Header/ui/SearchWidget/SearchWidget.tsx
  modules/Header/ui/SearchWidget/components/CategoriesList.tsx
  modules/Header/ui/SearchWidget/components/MainPanel.tsx
  modules/Header/ui/SearchWidget/components/SearchResults.tsx
  utils/index.ts
  utils/onPlainLeftClick.ts
Labels: bug

#1068 [DEV-12339] Fix - Some 404 urls produce error 500
  app/api/[...catch]/route.ts
  middleware.ts
Labels: bug

#1089 [CARE-4291] Update dependencies to get rid of security issues
  package-lock.json
  package.json
Labels: dependencies
